name: Build

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          #- StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          #- StandaloneWindows # Build a Windows standalone.
          #- StandaloneWindows64 # Build a Windows 64-bit standalone.
          #- StandaloneLinux64 # Build a Linux 64-bit standalone.
          #- iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          #- WebGL # WebGL.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      # temp comment out
      # - uses: actions/cache@v3
      #   with:
      #     path: Library
      #     key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
      #     restore-keys: |
      #           Library-${{ matrix.targetPlatform }}-
      #           Library-
      # this takes ~3 minutes
      # - if: matrix.targetPlatform == 'Android'
      #   uses: jlumbroso/free-disk-space@v1.3.1
      # this takes ~1 minute
      - name: Check disk space before cleanup
        run: df -h
      - if: matrix.targetPlatform == 'Android'
        name: Fast manual cleanup
        run: |
            sudo rm -rf /usr/local/lib/android       # ~9GB
            sudo rm -rf /opt/ghc                     # ~6GB
            sudo swapoff -a
            sudo rm -rf /mnt/swapfile                # ~4GB
            sudo rm -rf /usr/share/swift             # ~3-4GB
      - name: Check disk space after cleanup
        run: df -h
      - name: Extract version and build number
        id: versioning
        run: |
          version=$(cat Assets/Scripts/VersionNumber.txt | tr -d '\n')
          echo "baseVersionNumber=$version" >> $GITHUB_OUTPUT
          echo "fullVersionNumber=${version}+${{ github.run_number }}" >> $GITHUB_OUTPUT
      # test step for generating a dummy apk for testing build integrations without having to wait for longer Unity build
      - name: Generate fake APK
        if: matrix.targetPlatform == 'Android'
        run: |
          echo "Creating fake APK for ${{ matrix.targetPlatform }} build"
          mkdir -p build/${{ matrix.targetPlatform }}
          # write a tiny placeholder file named Android.apk
          echo "FAKE APK CONTENT" > build/${{ matrix.targetPlatform }}/Android.apk
      # - uses: game-ci/unity-builder@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #     BUILD_ENV: Staging
      #     GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      #   with:
      #     targetPlatform: ${{ matrix.targetPlatform }}
      #     customParameters: >
      #       -BUILD_ENV ${{ env.BUILD_ENV }}
      #       -GITHUB_BUILD_NUMBER ${{ env.GITHUB_BUILD_NUMBER }}
      #     androidKeystoreName: user.keystore # This file won't exist, but this property needs to exist
      #     androidKeystoreBase64: ${{ secrets.ANDROID_STAGING_KEYSTORE_BASE64 }}
      #     androidKeystorePass:  ${{ secrets.ANDROID_STAGING_KEYSTORE_PASS }}
      #     androidKeyaliasName:  ${{ secrets.ANDROID_STAGING_KEYALIAS_NAME }}
      #     androidKeyaliasPass:  ${{ secrets.ANDROID_STAGING_KEYALIAS_PASS }}
      - name: Rename output APK
        if: matrix.targetPlatform == 'Android'
        run: |
           mkdir -p final/${{ matrix.targetPlatform }} # have to copy renamed APK due to permission issues - can't just rename'
           cp build/${{ matrix.targetPlatform }}/Android.apk final/${{ matrix.targetPlatform }}/MandoUO-${{ steps.versioning.outputs.fullVersionNumber }}.apk
      - name: Upload Android artifact
        if: matrix.targetPlatform == 'Android'
        uses: actions/upload-artifact@v4
        with:
            name: Build-${{ matrix.targetPlatform }}-MandoUO-${{ steps.versioning.outputs.fullVersionNumber }}
            path: final/${{ matrix.targetPlatform }}
      - name: Upload non-Android artifact
        if: matrix.targetPlatform != 'Android'
        uses: actions/upload-artifact@v4
        with:
            name: Build-${{ matrix.targetPlatform }}-MandoUO-${{ steps.versioning.outputs.fullVersionNumber }}
            path: build/${{ matrix.targetPlatform }}
      # - uses: actions/upload-artifact@v4
      #   with:
      #       name: Build-${{ matrix.targetPlatform }}-${{ steps.versioning.outputs.fullVersionNumber }}
      #       path: build/${{ matrix.targetPlatform }}
      - name: Remove old MobileUO BleedingEdge Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        continue-on-error: true  # In case the tag/release doesn't exist yet
        with:
          delete_release: true
          tag_name: MobileUO-BleedingEdge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload MobileUO BleedingEdge Release
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: final/${{ matrix.targetPlatform }}/*
          name: 'MobileUO BleedingEdge Build v${{ steps.versioning.outputs.fullVersionNumber }}'
          body: |
            This is a bleeding-edge development build for `${{ matrix.targetPlatform }}`.

            Version: `${{ steps.versioning.outputs.fullVersionNumber }}`

            These builds may include incomplete or experimental features.
          tag: MobileUO-BleedingEdge
          makeLatest: false
          allowUpdates: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}